baseURL: https://arkadipta.github.io/
languageCode: en-us
title: Arkadipta
theme: PaperModX
params:
    # TocSide: 'left'
    # EnableInstantClick: true
    defaultTheme: auto
    ShowBreadCrumbs: true
    ShowShareButtons: true
    DateFormat: "2006"

    homeInfoParams:
        Title: üëãüèº Hi there,
        subtitle: "**welcome to my homepage...**"
        Content: |
          I am an **astrophysicist** specializing in the study of Very High 
          Energy (VHE) emissions from Supermassive Black Holes (SMBHs). I try to
          explain black hole physics phenomenologically through causal inference,
          time-series analysis, machine learning, stochastic calculus, and a 
          myriad of other data science techniques using the data collected from 
          numerous telescopes worldwide. I have also contributed to the software 
          development of three different telescopes worldwide. My passion lies 
          in working with large datasets and using statistics to make sense of 
          them.

          I completed my PhD at the Tata Institute of Fundamental Research 
          (TIFR), Mumbai and currently, I am working as a Postdoctoral Scientist 
          at Deutsches Elektronen Synchrotron (DESY), developing the array 
          control software and performing Monte-Carlo simulations for Cherenkov 
          Telescope Array (CTA). I also work on some interesting deep-learning 
          projects on the side. 
          
          Let's explore the cosmos through the lens of data and statistics.
        
        ShareButtons: ["linkedin", "twitter"]
        imageUrl: "/img/image.png"
        imageWidth: 180
        imageHeight: 180
        imageTitle: Potrait Arkadipta Sarkar
    
    profileMode:
      enabled: false # needs to be explicitly set
      title: ExampleSite
      subtitle: "This is subtitle"
      imageUrl: "/img/image.png"
      imageWidth: 120
      imageHeight: 120
      imageTitle: my image
      buttons:
          - name: Posts
            url: posts
          - name: Tags
            url: tags


    socialIcons:
      - name: twitter-simple
        url: "https://twitter.com/"
      - name: stackoverflow
        url: "https://stackoverflow.com/users/9504489/arkadipta-sarkar"
      - name: github-simple
        url: "https://github.com/Arkadipta"
      - name: linkedin-simple
        url: "https://www.linkedin.com/in/arkadipta-sarkar"
      - name: cv
        url: "/doc/CV_Long_AS.pdf"

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Notes
      url: /notes/
      weight: 2
    - name: Publications
      url: /posts/publications/
      weight: 3
    - name: Archives
      url: /archives/
      weight: 4


